const ADD_ITEM = 'ADD_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';

const ADD_MSG = 'ADD_MSG';
const DELETE_MSG = 'DELETE_MSG';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT = 'LOGOUT'
export {ADD_ITEM, DELETE_ITEM,ADD_MSG, DELETE_MSG, LOGIN_REQUEST, LOGIN_SUCCESS,LOGIN_FAILURE, LOGOUT}
