const ADD_ITEM = 'ADD_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

export {ADD_ITEM, DELETE_ITEM, LOGIN_REQUEST, LOGIN_SUCCESS,LOGIN_FAILURE}
